# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWvsVyGxWUu5utnPwVxtw6ZCgTrEhwqm
"""

import streamlit as st
import requests

# Streamlit UI untuk input pengguna
st.title('Prediksi Harga Berlian')

# Input dari pengguna
carat = st.number_input('Carat', min_value=0.0)
depth = st.number_input('Depth', min_value=0.0)
table = st.number_input('Table', min_value=0.0)
x = st.number_input('X', min_value=0.0)
y = st.number_input('Y', min_value=0.0)
z = st.number_input('Z', min_value=0.0)

# Ketika tombol ditekan
if st.button('Prediksi'):
    # Mengirimkan data ke FastAPI
    url = 'http://xxxxxx.ngrok.io/predict/'  # Gantilah dengan URL ngrok Anda
    data = {
        "carat": carat,
        "depth": depth,
        "table": table,
        "x": x,
        "y": y,
        "z": z
    }

    response = requests.post(url, json=data)

    if response.status_code == 200:
        result = response.json()
        predicted_price = result["predicted_price"]
        st.write(f"Prediksi Harga Berlian: {predicted_price:.2f}")
    else:
        st.write("Terjadi kesalahan dalam memproses permintaan.")