# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWvsVyGxWUu5utnPwVxtw6ZCgTrEhwqm
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pickle
import numpy as np

# Inisialisasi FastAPI
app = FastAPI()

# Load model yang sudah disimpan menggunakan pickle (misalnya model .pkl)
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Define input data model
class InputData(BaseModel):
    carat: float
    depth: float
    table: float
    x: float
    y: float
    z: float

# Endpoint untuk prediksi
@app.post("/predict/")
def predict(data: InputData):
    input_features = np.array([[data.carat, data.depth, data.table, data.x, data.y, data.z]])
    prediction = model.predict(input_features)
    return {"prediction": prediction[0]}